### ISSUE TITLE
Can't pass flags to put

### ISSUE THREAD

**Issue by da77a** [Venemo/node-lmdb#100]
LMDB has a significant optimisation for databases that are mostly appended to (rather than random inserts) that requires use of a flag on put promising to use a key larger than existing. There is no way to set flags on txn put operations.

**Comment by Venemo** [comment]
@da77a The reason why this isn't supported by node-lmdb at the moment is because this feature felt very easy to shoot yourself in the foot with. (And so, would result in data corruption and bug reports from lots of confused users.)

If you have an API proposal in mind, we can talk about it and I'll see what I can do.

**Comment by Venemo** [comment]
I now added the ability to specify put flags:

```js
txn.putString(dbi, key, data, { append: true });
```

Possible flags: `noDupData`, `noOverwrite`, `append`, `appendDup`. It doesn't seem to make sense to support `MDB_RESERVE` because it wouldn't save a `memcpy` from V8 to lmdb.

**Comment by Venemo** [comment]
@da77a Can you please test and see if this works for you?

**Comment by da77a** [comment]
I'll test shortly. But lgtm. I agree reserve is impractical, for a number of reasons. Re risks of append. It errors if you do the wrong thing - it will not corrupt the db: [openldap.devel discussion](http://comments.gmane.org/gmane.network.openldap.devel/8612). Thanks.

**Comment by Venemo** [comment]
@da77a Thanks for clearing that up! In that case, I'm not so worried about it anymore. If you do some tests, can you also please open a pull request with some test cases?

**Comment by Venemo** [comment]
I'm closing this issue now. Please reopen if you have any trouble with this.

**Comment by Venemo** [comment]
@da77a Oh and by the way ― congrats on making number #100 🥇
