### ISSUE TITLE
Build with node-gyp build error in Windows 7 Pro x64

### ISSUE THREAD

**Issue by drakiula** [Venemo/node-lmdb#101]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly loadAllDepsIntoIdealTree Finishing
20 silly loadIdealTree Finishing
21 silly currentTree node-lmdb@0.4.4
21 silly currentTree +-- assertion-error@1.0.2
21 silly currentTree +-- balanced-match@0.4.2
21 silly currentTree +-- benchmark@2.1.4
21 silly currentTree +-- bindings@1.2.1
21 silly currentTree +-- brace-expansion@1.1.6
21 silly currentTree +-- chai@3.5.0
21 silly currentTree +-- commander@2.3.0
21 silly currentTree +-- concat-map@0.0.1
21 silly currentTree +-- debug@2.2.0
21 silly currentTree +-- deep-eql@0.1.3
21 silly currentTree | `-- type-detect@0.1.1
21 silly currentTree +-- diff@1.4.0
21 silly currentTree +-- escape-string-regexp@1.0.2
21 silly currentTree +-- fs.realpath@1.0.0
21 silly currentTree +-- glob@3.2.11
21 silly currentTree +-- growl@1.9.2
21 silly currentTree +-- inflight@1.0.6
21 silly currentTree +-- inherits@2.0.3
21 silly currentTree +-- jade@0.26.3
21 silly currentTree | +-- commander@0.6.1
21 silly currentTree | `-- mkdirp@0.3.0
21 silly currentTree +-- lodash@4.17.4
21 silly currentTree +-- lru-cache@2.7.3
21 silly currentTree +-- minimatch@0.3.0
21 silly currentTree +-- minimist@0.0.8
21 silly currentTree +-- mkdirp@0.5.1
21 silly currentTree +-- mocha@2.5.3
21 silly currentTree +-- ms@0.7.1
21 silly currentTree +-- nan@2.5.1
21 silly currentTree +-- once@1.4.0
21 silly currentTree +-- path-is-absolute@1.0.1
21 silly currentTree +-- platform@1.3.3
21 silly currentTree +-- rimraf@2.6.1
21 silly currentTree | +-- glob@7.1.1
21 silly currentTree | `-- minimatch@3.0.3
21 silly currentTree +-- sigmund@1.0.1
21 silly currentTree +-- supports-color@1.2.0
21 silly currentTree +-- to-iso-string@0.0.2
21 silly currentTree +-- type-detect@1.0.0
21 silly currentTree `-- wrappy@1.0.2
22 silly idealTree node-lmdb@0.4.4
22 silly idealTree +-- assertion-error@1.0.2
22 silly idealTree +-- balanced-match@0.4.2
22 silly idealTree +-- benchmark@2.1.4
22 silly idealTree +-- bindings@1.2.1
22 silly idealTree +-- brace-expansion@1.1.6
22 silly idealTree +-- chai@3.5.0
22 silly idealTree +-- commander@2.3.0
22 silly idealTree +-- concat-map@0.0.1
22 silly idealTree +-- debug@2.2.0
22 silly idealTree +-- deep-eql@0.1.3
22 silly idealTree | `-- type-detect@0.1.1
22 silly idealTree +-- diff@1.4.0
22 silly idealTree +-- escape-string-regexp@1.0.2
22 silly idealTree +-- fs.realpath@1.0.0
22 silly idealTree +-- glob@3.2.11
22 silly idealTree +-- growl@1.9.2
22 silly idealTree +-- inflight@1.0.6
22 silly idealTree +-- inherits@2.0.3
22 silly idealTree +-- jade@0.26.3
22 silly idealTree | +-- commander@0.6.1
22 silly idealTree | `-- mkdirp@0.3.0
22 silly idealTree +-- lodash@4.17.4
22 silly idealTree +-- lru-cache@2.7.3
22 silly idealTree +-- minimatch@0.3.0
22 silly idealTree +-- minimist@0.0.8
22 silly idealTree +-- mkdirp@0.5.1
22 silly idealTree +-- mocha@2.5.3
22 silly idealTree +-- ms@0.7.1
22 silly idealTree +-- nan@2.5.1
22 silly idealTree +-- once@1.4.0
22 silly idealTree +-- path-is-absolute@1.0.1
22 silly idealTree +-- platform@1.3.3
22 silly idealTree +-- rimraf@2.6.1
22 silly idealTree | +-- glob@7.1.1
22 silly idealTree | `-- minimatch@3.0.3
22 silly idealTree +-- sigmund@1.0.1
22 silly idealTree +-- supports-color@1.2.0
22 silly idealTree +-- to-iso-string@0.0.2
22 silly idealTree +-- type-detect@1.0.0
22 silly idealTree `-- wrappy@1.0.2
23 silly generateActionsToTake Starting
24 silly install generateActionsToTake
25 silly generateActionsToTake Finishing
26 silly diffTrees action count 0
27 silly decomposeActions action count 0
28 silly runTopLevelLifecycles Starting
29 silly install runPreinstallTopLevelLifecycles
30 silly preinstall node-lmdb@0.4.4
31 info lifecycle node-lmdb@0.4.4~preinstall: node-lmdb@0.4.4
32 silly lifecycle node-lmdb@0.4.4~preinstall: no script for preinstall, continuing
33 silly executeActions Starting
34 silly install executeActions
35 silly doSerial global-install 0
36 silly doParallel fetch 0
37 verbose correctMkdir C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
38 verbose lock using C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\_locks\staging-27b72725b182b371.lock for D:\SRC\GO_WORK\src\github.com\drakiula\node-lmdb\node_modules\.staging
39 silly doParallel extract 0
40 silly doParallel preinstall 0
41 silly doReverseSerial remove 0
42 silly doSerial move 0
43 silly doSerial finalize 0
44 silly doSerial build 0
45 silly doSerial global-link 0
46 silly doParallel update-linked 0
47 silly doSerial install 0
48 silly doSerial postinstall 0
49 verbose unlock done using C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\_locks\staging-27b72725b182b371.lock for D:\SRC\GO_WORK\src\github.com\drakiula\node-lmdb\node_modules\.staging
50 silly executeActions Finishing
51 silly rollbackFailedOptional Starting
52 silly rollbackFailedOptional Finishing
53 silly install runPostinstallTopLevelLifecycles
54 silly build node-lmdb@0.4.4
55 info linkStuff node-lmdb@0.4.4
56 silly linkStuff node-lmdb@0.4.4 has D:\SRC\GO_WORK\src\github.com\drakiula as its parent node_modules
57 verbose linkBins node-lmdb@0.4.4
58 verbose linkMans node-lmdb@0.4.4
59 silly install node-lmdb@0.4.4
60 info lifecycle node-lmdb@0.4.4~install: node-lmdb@0.4.4
61 verbose lifecycle node-lmdb@0.4.4~install: unsafe-perm in lifecycle true
62 verbose lifecycle node-lmdb@0.4.4~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\SRC\GO_WORK\src\github.com\drakiula\node-lmdb\node_modules\.bin;C:\Users\IBM_ADMIN\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\IBM_ADMIN\bin;C:\Python36\Scripts;C:\Python36;C:\Python27;C:\Python27\Scripts;C:\tools\ruby23\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\IBM\Infoprint Select;C:\Program Files (x86)\IBM\Personal Communications;C:\Program Files (x86)\IBM\Trace Facility;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared;C:\Program Files (x86)\Common Files\Roxio Shared\13.0\DLLShared;C:\Program Files\Cloud Foundry;C:\Program Files\IBM\Bluemix\bin;C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\TShell\TShell;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files (x86)\IBM\IBM Bluemix Live Sync CLI;C:\tools\go\bin;D:\HashiCorp\Vagrant\bin;C:\Program Files\OpenVPN\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Program Files (x86)\Skype\Phone;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Program Files\nodejs;C:\notes;C:\Program Files (x86)\Microsoft VS Code\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Docker Toolbox;C:\tools\mingw64\bin;C:\Users\IBM_ADMIN\AppData\Local\atom\bin;C:\Users\IBM_ADMIN\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
63 verbose lifecycle node-lmdb@0.4.4~install: CWD: D:\SRC\GO_WORK\src\github.com\drakiula\node-lmdb
64 silly lifecycle node-lmdb@0.4.4~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
65 silly lifecycle node-lmdb@0.4.4~install: Returned: code: 1  signal: null
66 info lifecycle node-lmdb@0.4.4~install: Failed to exec install script
67 verbose stack Error: node-lmdb@0.4.4 install: `node-gyp rebuild`
67 verbose stack Exit status 1
67 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
67 verbose stack     at emitTwo (events.js:106:13)
67 verbose stack     at EventEmitter.emit (events.js:194:7)
67 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
67 verbose stack     at emitTwo (events.js:106:13)
67 verbose stack     at ChildProcess.emit (events.js:194:7)
67 verbose stack     at maybeClose (internal/child_process.js:899:16)
67 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
68 verbose pkgid node-lmdb@0.4.4
69 verbose cwd D:\SRC\GO_WORK\src\github.com\drakiula\node-lmdb
70 error Windows_NT 6.1.7601
71 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
72 error node v7.9.0
73 error npm  v4.2.0
74 error code ELIFECYCLE
75 error errno 1
76 error node-lmdb@0.4.4 install: `node-gyp rebuild`
76 error Exit status 1
77 error Failed at the node-lmdb@0.4.4 install script 'node-gyp rebuild'.
77 error Make sure you have the latest version of node.js and npm installed.
77 error If you do, this is most likely a problem with the node-lmdb package,
77 error not with npm itself.
77 error Tell the author that this fails on your system:
77 error     node-gyp rebuild
77 error You can get information on how to open an issue for this project with:
77 error     npm bugs node-lmdb
77 error Or if that isn't available, you can get their info via:
77 error     npm owner ls node-lmdb
77 error There is likely additional logging output above.
78 verbose exit [ 1, true ]

**Comment by Venemo** [comment]
@drakiula What exactly are you doing? How do you reproduce this problem?

**Comment by drakiula** [comment]
I cloned the repository on my Win 7 Pro x64 laptop, then ran "npm install" from within the root folder.

**Comment by Venemo** [comment]
@drakiula Here is what I did:

1. Created a clean Windows 7 Pro x64 virtual machine on VirtualBox
2. Downloaded and installed latest .NET Framework 4.6.2
3. Installed `windows-build-tools` and `node-gyp` with `npm`:
```
npm -g install windows-build-tools
npm -g install node-gyp
npm config set msvs_version 2015 --global
```
4. Build the module
```
cd node-lmdb
npm install
```

It seems to work for me. Even the tests are running.

```
npm run test
```

**Comment by Venemo** [comment]
Whoah, sorry, I just noticed that I was doing it on a 32-bit virtual machine, not x64. Let me find a 64-bit one.

**Comment by drakiula** [comment]
I was missing the MS build tools. Running "npm -g install windows-build-tools" has fixed this for me, sorry for the potential spam here :+1:

**Comment by Venemo** [comment]
@drakiula No problem. I'll document how I did it in the README so future users will hopefully have less trouble with it.

**Comment by Venemo** [comment]
@drakiula Take a look at https://github.com/Venemo/node-lmdb#building-node-lmdb-on-windows

**Comment by drakiula** [comment]
@Venemo Yes, I definitely confirm again this is working for Windows 7 x64. I was also able to run the tests and the benchmark without any errors. Thank you!
