### ISSUE TITLE
npm install fails "Error: node-lmdb@0.4.12 install: `node-gyp rebuild`"

### ISSUE THREAD

**Issue by nwbrad** [Venemo/node-lmdb#103]
New install on Centos 6.9
npm install -g  node-lmdb

Just install node.js last week.  Only other npm installed is sails.

[2017-05-04T19_17_31_611Z-debug.log.txt](https://github.com/Venemo/node-lmdb/files/977358/2017-05-04T19_17_31_611Z-debug.log.txt)

**Comment by Venemo** [comment]
@nwbrad The log doesn't seem very helpful... can you be more specific as to what exactly you tried to do?

**Comment by nwbrad** [comment]
Timur,

I haven’t done much, just installed node the other day.

Just installed sails today

And then tried to install node-lmdb.  It’s a pretty basic configuration.

 

I ran the install as root and ran the following command line:

npm install -g  node-lmdb

 

 

I had previously, a week ago, installed lmdb:

tar -xvzf LMDB_0.9.19.tar.gz

cd lmdb-LMDB_0.9.19/libraries/liblmdb/

make

sed -i 's| liblmdb.a||' Makefile

make prefix=/usr install

 

No issues with that.  Right now I’m trying to switch to node 6.1 to see if that makes a difference…

 

 

Thanks
Brad

**Comment by Venemo** [comment]
@nwbrad In your log the error message is `ELIFECYCLE` ― something I haven't seen on my own machine, ever. Googling this error code brings up a ton of different errors regarding `npm` and `node-gyp`...

Some clues:
* Can you try installing without the `-g` switch?
* Can you try on a different version of CentOS? 6.9 sounds like an old one.
* What happens if you `git clone` this repository and try to build it?

(Side note: `node-lmdb` contains LMDB bundled in, so it does not require LMDB itself to be installed on your system.)

**Comment by nwbrad** [comment]
Centos 6.9 is the current release of Centos 6.x, released April 2017.  Unfortunately I cannot use a different release since all our servers are on this release.

 

Removed Node and NPM and reinstalled, and basically the same problem.

 

Did the build from git clone and basically got the same message once it got to the step “node-gyp build”
Prior to that, no error messages.
 
The error messages start with:
../node_modules/nan/nan.h:45:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
 
And continues from there…
 
I did some research and it appears this is an issue with npm and node-gyp.
See: 
https://github.com/npm/npm/issues/12318
https://github.com/nodejs/node-gyp/issues/940
 
Rather than mess with the issue, I got around the problem by installing GCC 4.9x using the following:
sudo yum install centos-release-scl
sudo yum install devtoolset-3-toolchain
scl enable devtoolset-3 bash
 
GCC is now:  gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
 
See the following for more information:
https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/
 
Once this is done, I can build and I can install via the normal npm install -g node-lmdb
 
My only concern is if this affects anything else.  I have to keep plugging along and see what happens.
 
Thanks
Brad

**Comment by Venemo** [comment]
@nwbrad Hi Brad!

```
#error This version of node/NAN/v8 requires a C++11 compiler
```

I didn't notice this error message in your log, but yeah, this is important.  
Actually, `node-lmdb` itself is written in C++11, so you do need to have a C++11 compliant compiler if you want to use it. [Here is some information on which GCC versions support which C++ features.](https://gcc.gnu.org/projects/cxx-status.html)

So even though GCC 4.9 is very old, it should work. (I'm actually afraid to ask which version of GCC you had before.)

**Comment by Venemo** [comment]
@nwbrad I'll close this issue now, but if you still have any trouble with it, don't hesitate to re-open!
