### ISSUE TITLE
nested transactions

### ISSUE THREAD

**Issue by degifted** [Venemo/node-lmdb#104]
Hi @Venemo, why did not you implement nested transactions in your API? Any plans on that?

**Comment by Venemo** [comment]
@degifted Nobody has asked for this feature yet. I could look into it.

**Comment by degifted** [comment]
Thank you. This would address cases like the following:
Say, you are in a middle of long lived read-only transaction (an iterator over a big table) and at some point you need to update the index table corresponding to that table. After that, in order to see changes in the index, you would need to reset the original transaction (txn.reset(), txn.renew()). But this is not desirable since the big table may have been changed since you created the iterator.

**Comment by Venemo** [comment]
@degifted Nested transactions wouldn't help that use case, because the "long-lived" read-only transaction (and consequentally, all of its child transactions) would see the old state of the database.

**Comment by degifted** [comment]
You are right... It appears that rw transaction even cannot be opened under a ro transaction. It seems like it is suitable only for quite narrow set of use cases like complex cascade updates.

**Comment by Venemo** [comment]
@degifted Generally it doesn't make sense to open a nested read-only transaction. Nested transactions, in my opinion, are only useful in complicated update scenarios.

**Comment by Venemo** [comment]
@degifted One more thing. According to the LMDB docs, it is generally not a good idea to have long-lived transactions.

**Comment by Venemo** [comment]
@degifted With the above discussion in mind, are you still interested in nested transactions?

**Comment by Venemo** [comment]
Closing this issue due to lack of user interest in this feature.
