### ISSUE TITLE
Cursor.del doesn't work with dupsort databases when specifying both key and data

### ISSUE THREAD

**Issue by nwbrad** [Venemo/node-lmdb#106]
LMDB allows you delete duplicate keys by providing both the key and the value (for databases opened with MDB_DUPSORT).

I have created a database that allows dup keys and opened it with: 
            **keyIsUint32: true,
            dupSort: true,
            dupFixed: true,
            integerDup: true**
Both the key and the value are numbers (based on the definition I believe they would both be 32bit unsigned ints...)

Delete works fine if I specify just the key, but it deletes all the data as expected.
txn.del(dbiRelationship, key);
**txn.del(dbiRelationship, 16);**

However, when I try to delete one of the duplicate entries using both the key and value, I get an error:  "Specified key type doesn't match the key you gave."  The key is correct and if used alone (as shown above, it works fine).  The value is correct and exists...
txn.del(dbiRelationship, key, value);
**txn.del(dbiRelationship, 16, 256);**

I don't know whether I'm doing something wrong, or whether there is an issue with the library.  I searched, but did not find an example specifying both the key and the value when deleting.

Thanks

**Comment by Venemo** [comment]
@nwbrad Thanks for reporting this! I believe it's a regression in the last few releases. Can you please put together a simple, but complete test case that I could use to test your use case?

**Comment by Venemo** [comment]
If you have the time, even better would be if you could add it to the module tests and send me a pull request for that.

**Comment by nwbrad** [comment]
I have never done this before, so hopefully I did it correctly.
Added the file dupsort_delete.js
It is modeled after your dupsort.js, but it just has a case for the specific issue I encountered.
I tested with integer key and integer value.  But, but I imagine the same issue will happen with other values.

**Comment by Venemo** [comment]
@nwbrad Thanks! I'll take a look this weekend and get back to you.

**Comment by Venemo** [comment]
Sorry for taking so long, I've had some other stuff I needed to take care of. I'll look into this bug as soon as I can.

**Comment by nwbrad** [comment]
Thanks.

**Comment by Venemo** [comment]
@nwbrad The issue has been fixed and the fix has been release with v0.4.13 can you please take a look and see if it works for you?

**Comment by nwbrad** [comment]
Thanks.  It works for me now!

**Comment by Venemo** [comment]
Awesome, thanks!
