### ISSUE TITLE
Core dumps when dbi functions are assigned to a local, then called

### ISSUE THREAD

**Issue by anko** [Venemo/node-lmdb#11]
If I take e.g. `dbi.close` (or seemingly `dbi.`anything, really) and assign it to a local variable, calling that local variable crashes *node-lmdb* with a cryptic error.

Here's a test-case:

    var lmdb = require("node-lmdb");
    var env = new lmdb.Env();

    console.log("Opening env");
    env.open({
        "path"    : "./testdb",
        "max-dbs" : 1
    });

    console.log("Opening dbi");
    dbi = env.openDbi({
        name : "test1",
        create : true
    });

    /*
    // Works:
    console.log("Closing dbi");
    dbi.close();
    */

    // Dies:
    console.log("Assigning");
    var close = dbi.close;

    console.log("Closing dbi");
    close(); // <-- Here

This is the complete output, running the above example from `zsh` with `node` on a 64-bit Linux system:

    Opening env
    Opening dbi
    Assigning
    Closing dbi
    node: /home/aku/.node-gyp/0.10.22/src/node_object_wrap.h:61: static T* node::ObjectWrap::Unwrap(v8::Handle<v8::Object>) [with T = DbiWrap]: Assertion `handle->InternalFieldCount() > 0' failed.
    zsh: abort (core dumped)  node lmdb-closure-bug-testcase.js

JS functions are first class, so this is a sensible operation in JS-land, but it seems to confuse the underlying C++.

I'm on 7a12bd3 (currently newest master) and `node -v` is `v0.10.24`.

**Comment by Venemo** [comment]
@mikepb That's a reasonable thing, but it sounds like it would hurt performance. What do you think?

**Comment by mikepb** [comment]
I prefer writing more maintainable code JS than performant code for the simple reason that there are more people who can write JS than native bindings. For the same reasons, I don't use native bindings anymore...

**Comment by Venemo** [comment]
Okay!
