### ISSUE TITLE
Support for MDB_NOLOCK

### ISSUE THREAD

**Issue by Bibliofile** [Venemo/node-lmdb#113]
I am using this library to access the same database across two applications. The first application manages the database and the second application will only read from the database. 

In order for this to work, when calling `env.open` I need to be able to supply the `MDB_NOLOCK` flag. I've [forked](https://github.com/Bibliofile/node-lmdb) the project and added `noLock` as an option when calling `env.open`, however I'll be the first to admit I really don't know what I'm doing here. Given some of the comments in the source and issue discussions, it sounds like there may be some problems with this that I am unaware of. Would this change be an acceptable addition to this module?

**Comment by Venemo** [comment]
@Bibliofile Why exactly do you need `MDB_NOLOCK`? Multiple processes should be able to access the same database without any special flag.

**Comment by Venemo** [comment]
The docs of `MDB_NOLOCK`:

```
Don't do any locking. If concurrent access is anticipated, the caller must manage all concurrency itself. 
```

Why would you want to do that?

**Comment by Bibliofile** [comment]
> Why would you want to do that?

I really don't, however the database creation and management is managed by a program which is not under my control. Without the `MDB_NOLOCK` option I am unable to access the database.

**Comment by Venemo** [comment]
@Bibliofile Thinking this through again, I think your app should be able to open the same database even without `MDB_NOLOCK`. What kind of results do you get when you try?

**Comment by Bibliofile** [comment]
It's been a few months since I looked at this project - so I can't recall exactly the error (I've also apparently lost the VM where it was stored). If I recall correctly, I was getting access errors. I'll try to find it and check sometime this week.

**Comment by Venemo** [comment]
@Bibliofile Please check.

**Comment by Venemo** [comment]
Hi!

As of d27408aed06fde656f70d49c09876726d9aac87d I added unofficial support for `MDB_NOLOCK`. Though I would definitely recommend against using it, unless you find it absolutely necessary.

**Comment by Venemo** [comment]
In case you do need it:

```
env.open({
    path: "./testdata",
    maxDbs: 10,
    unsafeNoLock: true
});
```

**Comment by Venemo** [comment]
@Bibliofile If you need any further help with this, feel free to open a new issue.
