### ISSUE TITLE
SIGABRT when using `noOverwrite` flag

### ISSUE THREAD

**Issue by paberr** [Venemo/node-lmdb#117]
I was just playing around with the `noOverwrite` flag for the put methods of a transaction,
when I stumbled across the following SIGABRT:
```
node(42986,0x7fffb7892340) malloc: *** error for object 0x105806bf8: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
fish: 'node test.js' terminated by signal SIGABRT (Abort)
```

The following snippet should reproduce the error.
```javascript
var lmdb, env, dbi;

lmdb = require('node-lmdb');
env = new lmdb.Env();
env.open({
    // Path to the environment
    path: "./testdata",
    // Maximum number of databases
    maxDbs: 10
});

dbi = env.openDbi({
   name: "example7",
   create: true
});

var txn;

txn = env.beginTxn();
txn.putNumber(dbi, "hello", 7);
txn.putNumber(dbi, "hello", 8, { noOverwrite: true }); // <- This line causes the crash.
txn.commit();
dbi.close();
env.close();
```

Unfortunately, I haven't had the time for any debugging yet.
But I thought it might be worth reporting it to you.

**Comment by Venemo** [comment]
@paberr Yes, thanks for reporting this. I will try to debug it as soon as I can.

**Comment by Venemo** [comment]
On a first try, it results in `SIGSEGV` for me. There is definitely something wrong going on here.

**Comment by Venemo** [comment]
@paberr I pushed a fix for this, can you give it a try?

**Comment by paberr** [comment]
Thanks, works perfectly now! 👍 
But found another SIGSEGV that I will report separately.
