### ISSUE TITLE
SIGSEGV when closing an environment after exception

### ISSUE THREAD

**Issue by paberr** [Venemo/node-lmdb#119]
The SIGSEGV is reproducible as follows:
1. I open a transaction and perform an operation, which throws an exception.
2. I catch the exception and try closing the database/environment without aborting the transaction.

If I manually abort the transaction between step 1 and 2, everything works fine.
However, if I understood correctly, `cleanupStrayTxns` should actually take care of cleaning up this transaction.

Here's a code snippet to reproduce the error.
```javascript
var lmdb, env, dbi;

lmdb = require('.');
env = new lmdb.Env();
env.open({
    // Path to the environment
    path: "./testdata",
    // Maximum number of databases
    maxDbs: 10
});

dbi = env.openDbi({
   name: "example7",
   create: true
});

var txn;

txn = env.beginTxn();
txn.putNumber(dbi, "hello", 7);
try {
  txn.putNumber(dbi, "hello", 8, { noOverwrite: true });
} catch (e) {
  console.log('Already exists');
}
// We forgot the abort intentionally:
// txn.abort();
dbi.close();
env.close(); // <- This line causes the crash.
```

**Comment by Venemo** [comment]
Thanks for reporting this.  
The crash actually comes from `cleanupStrayTxns`...

**Comment by Venemo** [comment]
@paberr Looks like the `cleanupStrayTxns` code was never exercised with a stray write transaction. Take a look if it's okay for you now. :)

**Comment by paberr** [comment]
Looks good. :)
Thank you for the quick response!
