### ISSUE TITLE
Commit 4b08d7f introduces changes that prevent compilation on Windows 8.1

### ISSUE THREAD

**Issue by jeffesquivels** [Venemo/node-lmdb#122]
Hi,

It seems commit [`4b08d7f0de936775eec6caa7c642077e24a0904a`](https://github.com/Venemo/node-lmdb/commit/4b08d7f0de936775eec6caa7c642077e24a0904a) introduces changes from commit [`e85ae1fe883b4847f07cfebc2630636d06e429c3`](https://github.com/LMDB/lmdb/commit/e85ae1fe883b4847f07cfebc2630636d06e429c3) in upstream repository and this breaks compilation on Windows 8.1 (the only one I have available for testing) using `windows-build-tools` so that following the [instructions](https://github.com/Venemo/node-lmdb#building-node-lmdb-on-windows) will no longer work.

Manually reverting upstream to the previous commit [`55fcd0cfee1cb4bbe1033a3efbad9795f79d4014`](https://github.com/LMDB/lmdb/commit/55fcd0cfee1cb4bbe1033a3efbad9795f79d4014) enables successful compilation again, in case this workaround can be implemented while upstream fixes this.

Thanks!

**Comment by jeffesquivels** [comment]
I asked [about this](https://www.openldap.org/lists/openldap-technical/201804/msg00003.html) on the `openldap-technical` mailing list and it seems that LMDB compilation is only officially supported on Windows when using  GCC (not MSVC), so now this may be a documentation issue instead of a compilation one.

I also received the suggestion of using [libmdbx](https://github.com/leo-yuriev/libmdbx) for Windows, but it was also stated that their API is different from LMDB, so this may not be an option.

**Comment by Venemo** [comment]
@jeffesquivels I see a few possible ways to move forward with it:

1. Patch LMDB locally so at least this module will compile --- in this case, a PR is welcome
2. Somehow tell node-gyp that this should be compiled with GCC on Windows --- is this even possible?
3. Revert to old LMDB --- but I would very much prefer not to do this.

**Comment by jeffesquivels** [comment]
I was doing a bit of research on this, it seems that option `2.` is not possible because the node.js executable in Windows is compiled with Visual Studio [and it cannot load modules compiled with GCC](https://github.com/nodejs/node-gyp/issues/402#issuecomment-35316212).

So we're left with `1.` or `3.`; since `1.` is preferred, I tried two approaches to it:

  1. Apply a patch that will only revert the specific commit that breaks things directly to `node-lmdb`.
  2. Create a fork of `LMDB`, apply the same patch as `1.` to this fork, and then use that as the origin for the `git subtree` in `node-lmdb/dependencies/lmdb`.

You can see both approaches in [here](https://github.com/jeffesquivels/node-lmdb/tree/revert_breaking_commit) and [here](https://github.com/jeffesquivels/node-lmdb/tree/use_fixed_lmdb) respectively.

I also tested [here](https://github.com/jeffesquivels/node-lmdb/tree/revert_then_upstream) that after doing `1.` you can still update the `git subtree` from the official LMDB mirror repo on github and it worked fine too.

So I guess now it depends on which of this two approaches you think would be better to send the corresponding PR.

**Comment by Venemo** [comment]
Thanks @jeffesquivels for your effort. I believe `1` is simpler, especially if it doesn't break the `git subtree` magic. Looking forward to the PR! :+1:
