### ISSUE TITLE
Latest packaged version contains huge binary files

### ISSUE THREAD

**Issue by jeffesquivels** [Venemo/node-lmdb#125]
The [latest packaged](https://registry.npmjs.org/node-lmdb/-/node-lmdb-0.5.4.tgz) version seems to contain a couple of huge binary files:

  * vgcore.17237 (675M)
  * vgcore.17437 (166M)

They seem to be unnecessary for the normal operation of `node-lmdb` (and according to a quick search on the web, they seem to be debugging files from Valgrind).

If they're indeed unneeded, may be it would be better to remove them from the package.

**Comment by Venemo** [comment]
I fixed it now. Sorry for the inconvenience!

**Comment by jeffesquivels** [comment]
@Venemo no problem, thank you very much! :)
