### ISSUE TITLE
Prebuilt Binaries

### ISSUE THREAD

**Issue by kriszyp** [Venemo/node-lmdb#147]
It could be helpful, both for users with difficulties installing build tools, and just for faster installs, to offer prebuilt binaries. We have node-lmdb users that would benefit from this. NPM has good support for this, and it is part of some other projects. The downside is that it requires running the prebuild script for each release. I would be glad to write a PR to add the prebuild-install script/configuration so that it uses the pre-built binaries on install, but up to you (@Venemo ) if you want to start doing the prebuild scripts on release (It is possible to publish release to a different repo, but the package.json would have to point to that repo).

**Comment by Venemo** [comment]
Yes, sounds like this is something worth doing. Why it isn't done yet is NPM didn't have a way to do it when I last checked. Thanks for the offer! If you don't mind, I'd like to take you up on it.

**Comment by Venemo** [comment]
Can this issue be closed?

**Comment by kriszyp** [comment]
Yes, I believe so!
