### ISSUE TITLE
Support for Node 12

### ISSUE THREAD

**Issue by kriszyp** [Venemo/node-lmdb#149]
Add support for Node version 12, which I think is dependent on https://github.com/nodejs/nan/issues/849.

**Comment by josephg** [comment]
Nan supports node 12. In that thread @bnoordhuis [says many issues are caused by old nan versions](https://github.com/nodejs/nan/issues/849#issuecomment-488292298)

**Comment by kriszyp** [comment]
Yeah, this is fixed by #150, there is nothing wrong with Nan.

**Comment by innerop** [comment]
Hi,

Thinking of trying this library. Is this still an open issue?

**Comment by Venemo** [comment]
@innerop I've just merged the PR that addresses it. Will push a new release to NPM soon.

**Comment by Venemo** [comment]
With the release of 0.8.0 on npm, I think this issue can be closed now.
