### ISSUE TITLE
node-gyp error

### ISSUE THREAD

**Issue by andyahn91** [Venemo/node-lmdb#152]
I am installing `node-lmdb` on my debian, and I am having several issues.

I have tried:
- removing `node_modules` in the same directory
- removing `package-lock.json` in the same directory
- removing `.node-gyp` in home directory
- uninstalling `node-gyp` globally
- installing Node.js v10.x (which caused the similar issue on other application as well)
- `apt install`ing `build-essential` and `g++`

(edit) - After upgrading npm version to 6.12.0, gyp err shows `gyp ERR! node-gyp -v v5.0.5`

Any help??

![Fullscreen_10_8_19__11_15_AM](https://user-images.githubusercontent.com/38708867/66422001-bff36180-e9bd-11e9-9b4c-50c4fb2b9a0a.png)

**Comment by Venemo** [comment]
I will have to check, I don't think I tried node v10 yet.

**Comment by Venemo** [comment]
Can you try if version 0.8.0 fixes this problem?

**Comment by kriszyp** [comment]
With prebuildify I am building against multiple node versions, so I am pretty sure that has been addressed.
