### ISSUE TITLE
Get() Should accept a default value to be returned when key is not found

### ISSUE THREAD

**Issue by KrishnaPG** [Venemo/node-lmdb#153]
https://github.com/Venemo/node-lmdb/blob/0f2f2e7ef930136342d618d74ad8f27f66247ea4/src/txn.cpp#L197-L199

When the key is not found, currently the code always returns `null`. It should accept a default value to be returned, instead, when the given key is not found. For example:
````
get(key, defVal) {
  if(key is not found) return defVal;
}
````

**Comment by Venemo** [comment]
If you desire a default value, you can use JavaScript.

```
var value = txn.getString(dbi, 42) || "Your default value"
```

I don't think it's a good idea to bloat node-lmdb with such features, but if you feel like implementing it, a pull request is always welcome.

**Comment by Venemo** [comment]
I hope the answer I provided is clear. I'm closing this issue now due to lack of response from the OP.
