### ISSUE TITLE
How to avoid override existing key/value when put?  dup set to be false.

### ISSUE THREAD

**Issue by f4f5** [Venemo/node-lmdb#154]
i see there is implementation in python 
https://lmdb.readthedocs.io/en/latest/#put

I can't find any document about it.  cry~~

**Comment by Venemo** [comment]
What exactly is the problem you are trying to solve? How have you tried to solve it?

**Comment by beenotung** [comment]
@f4f5 do you mean to put value only if it's not put before?
If so, you may use wrapper functions, e.g.
```javascript
txn.setString = (key, value, keyType) => {
  let value = txn.getString(key, keyType)
  if (value === null) {
    txn.setString(key, value, keyType)
  }
}
```

**Comment by Venemo** [comment]
Yes, I think @beenotung has the correct answer here. Due to lack of response from OP, I'm closing this issue now.
