### ISSUE TITLE
opening env causes mdb file to be created with full size on Windows 10 build 1909.

### ISSUE THREAD

**Issue by dents** [Venemo/node-lmdb#159]
```
  const env = new nodeLMDB.Env();
  env.open({
    path: './test/',
  });

```
On Linux this creates a 32768 byte data.mdb file as expected which then grows it as needed up to mapSize. But on Windows 10, data.mdb is 1,048,576 (default mapSize value) instantly on startup. Setting it to more than available disk space causes "Error: There is not enough space on the disk."  Setting it to something massive that still fits on disk (i.e. 500GB) causes the file to be instantly created, suggesting some sort of memory-mapped Windows shenanigans. Just calling it out because there are forum threads that suggest using 1TB for mapSize to avoid having to call resize() which used to work, but no longer does. I tested with Node v12 on both Windows and Linux.

**Comment by Venemo** [comment]
I think this has to do with the differences of how memory maps work between the different operating systems, or at least how LMDB makes use of the memory map.

Unfortunately it has been some time since I last looked at how it works, but AFAIK this has been a problem with LMDB for some time, and is not something that node-lmdb can fix.

**Comment by Venemo** [comment]
I think there have been some patches floating around which addressed this issue on Windows, but I'm unsure if they have been included in any upstream release of LMDB. @hyc could you please give us a hint about this?

**Comment by kriszyp** [comment]
LMDB's master branch (mdb.master) actually behaves this way, using a different Windows API for memory mapping that uses dynamic growth of the file size, as further segments of the memory map are written. And node-lmdb should probably upgrade to the latest mdb.master at some point, as it is a lot more stable. However, as far as the dynamic memory mapping:

Don't use it.

It is a disaster for performance. It causes random lockups of as the file size grows, in very inconsistent and erratic fashion. It took us weeks to track random freezing on our servers until we finally tracked it down to this. I actually recently committed a patch (it was recently merged) to LMDB that allows you to explicitly disable this feature (it will be a MDB_FIXEDSIZE compiler definition). Windows just doesn't have good support for this. I think node-lmdb should upgrade, but should make sure this compiler option is enabled (disabling dynamic growth on Windows).

For dynamic database growth, consider using lmdb-store (https://github.com/DoctorEvidence/lmdb-store), which is a package that layers on top of node-lmdb and automatically manages map/file size for you, resizing the database automatically as it gets full. This uses standard Windows memory maps and resizes them as needed and has much better performance and stability.

**Comment by Venemo** [comment]
That's good to know, thanks Krys. About upgrading to the latest LMDB: pull requests are welcome. Sadly I don't have much time to spend on node-lmdb these days.

**Comment by kriszyp** [comment]
In 0.9.4, we are using the latest LMDB version with MDB_FIXEDSIZE off by default, which should allow for dynamic growth on Windows, but also includes documentation warnings about its impact on performance and build option to disable it and using more stable/predictable fixed size files.
