### ISSUE TITLE
Node 13 support

### ISSUE THREAD

**Issue by micburks** [Venemo/node-lmdb#160]
Is Node 13 support ready to be released? I see that it was addressed in a recent commit

**Comment by Venemo** [comment]
@micburks You could speed things up if you could test the latest master of node-lmdb on Node 13. I'm currently quite busy with other stuff, but if you can confirm that it works, I can make the release.

**Comment by micburks** [comment]
I tried in a couple projects that use `node-lmdb` and I don't see any obvious regressions in Node 13 or any previous versions.

**Comment by Venemo** [comment]
Awesome, thanks for your feedback. I just published version 0.8.0, let me know if it works for you.

**Comment by micburks** [comment]
Much thanks!
