### ISSUE TITLE
Change prebuild infrastructure to use prebuildify

### ISSUE THREAD

**Issue by Raynos** [Venemo/node-lmdb#162]
https://github.com/prebuild/prebuildify and https://github.com/prebuild/node-gyp-build

It looks like the `prebuild` module has been superceeded by `prebuildify`

The approach of the latter is to put all the prebuilt binaries in the npm tarball. This replaces the `prebuild-install` library which downloads binaries at install time.

If the binaries already exist in the npm tarball then there's no need to do extra work at `install` time.

**Comment by kriszyp** [comment]
Switched to using prebuildify. Feel free to check if I am doing correctly, since it seems that it is only prebuilding for Windows, since I am doing dev on Windows. Or maybe that's a good thing, because Windows is the hardest OS to get binary addons to build?

**Comment by Raynos** [comment]
Thanks kris ! I’ll take a look when I get a chance
