### ISSUE TITLE
Cursor still seems to leak memory

### ISSUE THREAD

**Issue by black-hawk85** [Venemo/node-lmdb#165]
The cursor still seems to leak memory

Here's a very simplified test code to reproduce this issue

```
  getEntries() {
    var txn = env.beginTxn();
    var ret = []

    // Test return value
    for (var i = 0; i < 1024*1024; i++) {
      ret[i] = i
    }

    var cursor = new lmdb.Cursor(txn, this.db);
    cursor.goToLast()
    cursor.close()
    cursor = null

    txn.commit()
    txn = null
    return ret
  }
```
As soon as ```ret``` is as freed by garbage collector,
```process.memoryUsage().rss``` comes down to 90 MB in my application.

Now if I start iterating the cursor the memory will increase and never come back down again
```
  getEntries() {
    var txn = env.beginTxn();
    var ret = []

    // Test return value
    for (var i = 0; i < 1024*1024; i++) {
      ret[i] = i
    }

    var cursor = new lmdb.Cursor(txn, this.db);
    for (var found = cursor.goToLast(); found !== null; found = cursor.goToPrev()) {
    }
    cursor.close()
    cursor = null

    txn.commit()
    txn = null
    return ret
  }
```
```process.memoryUsage().rss``` will stay at 115 MB, also when I try to initiate garbage collector manually.

In this test I had 14 instances of my wrapper class with following amount of data in LMDB:
1.16 MB
1.32 MB
99.47 KB
163.93 KB
2.03 MB
1.32 MB
2.05 MB
1.23 MB
1.12 MB
1.32 MB
163.82 KB
1.11 MB
224.83 KB
2.05 MB
Total: approx 15 MB

As I make a lot of read operations my application runs out of memory after some time and I think this might be the cause.

**Comment by kriszyp** [comment]
Operating systems are... interesting in how they attribute RSS memory. LMDB uses memory-mapped files for its database. This means that the LMDB is getting a direct reference to the OS's memory used to cache and map to files on disk. Whenever you access a file, the OS loads that file into its cache. With memory mapped files, the process gets a direct reference to that memory. And with that the OS will attribute that memory to your process. However, it is important to know that there whether the OS attributes that memory to your process or not basically makes no difference in how much real memory is being used by your computer. If you scan a 100MB file with standard file APIs (no memory mapping), the OS will load that 100MB into memory, and it will stay in memory (cached) until some other process (or your process) needs that memory (and it hasn't been recently accessed, but it won't show up as any memory usage for your process (and the cached data can stay in memory for a long time if the computer isn't doing much else). If you scan that file with memory-mapping, the OS will perform essentially exactly the same process, taking exactly the same RAM, and still be just as free to swap the data from that file out of memory in the future (memory mapping doesn't prevent swapping out of RAM), the only difference is it will "report" that memory as being attached your process. But there is *no* real difference in actual RAM used. The only way that RSS reported can ever actually drop is if the OS decides to swap it out to use for something else. So all that RSS memory is essentially actually "available" memory to the OS, and really isn't something you should worry about (are servers often report over 10GB of RSS/shared memory, but they consistently stay below 500MB of real private memory, and the shared memory goes down anytime other processes start needing memory). In Node, you *should* be worried about the `heapUsed` and `external` memory. If those go up without ever coming down, then you have a memory leak.
