### ISSUE TITLE
Wrap mdb_set_compare

### ISSUE THREAD

**Issue by Venemo** [Venemo/node-lmdb#17]
Create a wrapper for `mdb_set_compare`.

**Comment by Venemo** [comment]
There seems to be no interest for this feature at this time, so I'm closing the issue now. Please reopen if you are interested in seeing this feature.

**Comment by NodeGuy** [comment]
I'm interested.  I'm trying to create a Datomic-like database with [an EAVT index](https://docs.datomic.com/pro/query/indexes.html) in which EAV are sorted in ascending order and T is in descending order.
