### ISSUE TITLE
Do you need to db.close for all transactions?

### ISSUE THREAD

**Issue by trotter2000** [Venemo/node-lmdb#176]
Wondering as I made a simple collections function where you can add/remove a variable to an array. After doing "getString" you need to "db.open" again before I could write or even do get again, so it seems like "get" automatically closes after. 

Going by the usage info it says to make sure you close things after use. It's not a big deal I know, I could just use close anyway as it doesn't error if you closed twice however I don't want to use unnecessary code if I can. Bit OCD about things like that :) 

putString on the other hand clearly stays open till you close it.

**Comment by kriszyp** [comment]
I believe this might be more related to the transactions you are using. If you open a db using a transaction and then commit that transaction, the db stays open. If you abort or reset the transaction, then the db gets closed, and perhaps you are reseting or aborting the read transaction you are using for getString (reseting is actually best practice for read-only transactions, once you have permanently opened the db)?

**Comment by kriszyp** [comment]
Also, in regards to if you should close databases, the LMDB documentation itself recommends against every closing dbs (and I never close dbs in my code): http://www.lmdb.tech/doc/group__mdb.html#ga52dd98d0c542378370cd6b712ff961b5

**Comment by trotter2000** [comment]
> I believe this might be more related to the transactions you are using. If you open a db using a transaction and then commit that transaction, the db stays open. If you abort or reset the transaction, then the db gets closed, and perhaps you are reseting or aborting the read transaction you are using for getString (reseting is actually best practice for read-only transactions, once you have permanently opened the db)?

Thanks for the replys. I think I've been working to long without a break on a rather warm day. I was sure I proven what I was saying before I posted. Now that I finished and cleaned up what I was coding it seems to not be the case. Got a feeling I was using get from the class I made that has the close in it and not getString :open_mouth: 



> Also, in regards to if you should close databases, the LMDB documentation itself recommends against ever closing dbs (and I never close dbs in my code): http://www.lmdb.tech/doc/group__mdb.html#ga52dd98d0c542378370cd6b712ff961b5

I wasn't very clear as I said db.close as that is the function I used for closing, not sure why I even made it as it's only 2 lines lol. Anyway what I meant to say was dbi.close() and env.close().

Now I have cleared that up. I want to make sure your not talking about dbi/evn.close() anyway. I have noticed how nothing seems to go wrong when you don't do dbi/evn.close(). Yet the README says to close them up when your finished. So I'm a little lost. Other than closing, the rest of the info is very clear to me and easy to understand, so wanted to say thanks for the great work. Glad I didn't follow the sheep and just use mongodb, love how I don't need to run anything else outside of node.

**Comment by kriszyp** [comment]
I never close environments or databases when I use LMDB in node. If you really know that you aren't going to use an environment again, you can close it to free up the bit of memory it was using, but that's rarely necessary, generally you just open an environment when you start your program and leave it open (the memory will be cleaned up on process exit). As far as cleanup concerns, the more important consideration is closing transactions. Leaving write transactions open blocks other threads/processes and leaving read transactions open for too long prevents reclamation of free-space, and you can run out of reader slots if you have a lot of overlapping processes that don't close transactions before exiting. Some of this is dependent on OS, but LMDB does try to do some cleanup of stale locks.

**Comment by trotter2000** [comment]
> I never close environments or databases when I use LMDB in node. If you really know that you aren't going to use an environment again, you can close it to free up the bit of memory it was using, but that's rarely necessary, generally you just open an environment when you start your program and leave it open (the memory will be cleaned up on process exit). As far as cleanup concerns, the more important consideration is closing transactions. Leaving write transactions open blocks other threads/processes and leaving read transactions open for too long prevents reclamation of free-space, and you can run out of reader slots if you have a lot of overlapping processes that don't close transactions before exiting. Some of this is dependent on OS, but LMDB does try to do some cleanup of stale locks.

Thanks for clearing things up for me. No need to save a little ram, saving plenty by using LMDB from my research. Not that I need super read speed however it's nice knowing it's faster than any of the other options I was recommend to use.
