### ISSUE TITLE
{Question] Environment size and Delete

### ISSUE THREAD

**Issue by zaxharperdb** [Venemo/node-lmdb#179]
I created a db table with 10GB, I am inserting a small record,
{
  id: <guid>,
  tagname: 'ARRAY_DINT[1]',
  timestamp: '2020-10-07 07:39:12.793367+00:00',
  value: 556716
}

I am deleting every minute, about 2400 records, eventually, the DB size is hit and the DB is not responsive?
https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/
This article makes me feel like as I mark areas for deletion they should get flagged to be over written.
I am streaming these objects in at about 43 records a second.
And Deleting everything older than 5 minutes every minute.

Your expertise is always appreciated.

**Comment by kriszyp** [comment]
Is it possible that you have a read transaction open somewhere that is staying open? If you have an open read transaction this will prevent any data that is newer than the earliest open read transaction (even if later deleted) from being reclaimed as free space.

**Comment by zaxharperdb** [comment]
Aha.. good point!
Possibly, inadvertently.. The program is doing only writes, but the studio db manager is spectating..Thank you for your insight.
