### ISSUE TITLE
mdb_copy: copying failed, error -30784 (MDB_INCOMPATIBLE: Operation and DB incompatible, or DB flags

### ISSUE THREAD

**Issue by C3Pool** [Venemo/node-lmdb#191]
I run: mdb_copy -c /root/service_db /root/lmdb_new
Then It errors: mdb_copy: copying failed, error -30784 (MDB_INCOMPATIBLE: Operation and DB incompatible, or DB flags changed)

**Comment by kriszyp** [comment]
Are you using the same version of LMDB that you used to create the database? node-lmdb's build doesn't build mdb_copy, I don't think, so not sure if you are building from the same source/version?

**Comment by C3Pool** [comment]
It has been solved by redo, although it is still not found why this error is caused. All versions are correct.
