### ISSUE TITLE
Test on Windows

### ISSUE THREAD

**Issue by Venemo** [Venemo/node-lmdb#2]
Test if node-lmdb can be built on Windows and test it by running the example code in the repository.

**Comment by Venemo** [comment]
@JuniperChicago Is there a way to specify the minimum msvs version in the `binding.gyp` or `package.json` somehow?

**Comment by JuniperChicago** [comment]
@Venemo I have to make a correction regarding the success of my build. I merged [onilabs/node-lmdb/commit/a43d460eb1bbcd4160c6fc117509c42d36e39094](https://github.com/onilabs/node-lmdb/commit/a43d460eb1bbcd4160c6fc117509c42d36e39094) then used `-msvs_version-2013` on the command line where the build spews lots of warnings but completes. As to your question, I do not know how to specify minimum msvs version other than at the command line.

**Comment by Venemo** [comment]
Thank you @JuniperChicago :) I have a few more questions:

* Does it actually work with your patches and `-msvs_version-2013`?
* Could you pastebin the full output of the thing including warnings and everything?

**Comment by JuniperChicago** [comment]
@Venemo Here is the [pastebin](http://pastebin.com/wWjdc9nt) with my console.log output. Yes, the build works fine building off my [fork](https://github.com/JuniperChicago/node-lmdb), which I am calling from 'package.json'. Although I am getting some weirdness where `txn.putString()` is somehow causing `keyIsUint32` error to be returned even though I am using a string for the key and I do not have the store set to expect `Uint32' types for keys, but I can avoid the situations where this error comes up so far.

**Comment by Venemo** [comment]
@JuniperChicago Thanks for your help! About this `keyIsUint32` error, could you give me some code that shows when it happens?

**Comment by JuniperChicago** [comment]
@Venemo Thanks for the help. I managed to sort out the ordering of transactions and edge cases cases where I was escaping functions before transactions were closed. So, I this error is not an issue anymore. Again, thanks.

**Comment by Venemo** [comment]
@JuniperChicago That's nice, but I'd still appreciate a sample code to reproduce the issue. Maybe I can add more meaningful error messages.

**Comment by delaneyj** [comment]
on a windows 10 box with Node.js 5.2 and VisualStudio 2013 (able to compile other project like redis' c/c++ without issue so evn flags are all setup and working).

```
cd \
mkdir test
npm install --msvs_--save version=2013 node-lmdb
```

getting this as output.
```
> node-lmdb@0.3.0 install C:\test\node_modules\node-lmdb
> node-gyp rebuild


C:\test\node_modules\node-lmdb {git}
{lamb} if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  mdb.c
  midl.c
  win_delay_load_hook.c
..\libraries\liblmdb\midl.c(43): warning C4267: 'initializing' : conversion from 'size_t' to 'unsigned int', possible loss of data [C:\test\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\libraries\liblmdb\midl.c(147): warning C4267: '+=' : conversion from 'size_t' to 'unsigned int', possible loss of data [C:\test\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\libraries\liblmdb\midl.c(177): warning C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data [C:\test\node_modules\node-lmdb\build\node-lmdb.vcxproj]
..\libraries\liblmdb\mdb.c(76): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\test\node_modules\node-lmdb\build\node-lmdb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\test\node_modules\node-lmdb
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON test@1.0.0 No description
npm WARN EPACKAGEJSON test@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs_version=2013" "--save" "node-lmdb"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! node-lmdb@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-lmdb@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-lmdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-lmdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\test\npm-debug.log
```

I know this is an old thread but seeing if there is a known fix.

**Comment by Venemo** [comment]
@delaneyj The trouble seems to be this line:

```
..\libraries\liblmdb\mdb.c(76): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\test\node_modules\node-lmdb\build\node-lmdb.vcxproj]
```

So it's one of LMDB's source files that would need `unistd.h` which it can't find.  
I'd need to look around and see what needs to be done to build LMDB on Windows.

**Comment by delaneyj** [comment]
Not sure but would a [library like this one](http://www.codeproject.com/Articles/157001/Full-getopt-Port-for-Unicode-and-Multibyte-Microso) provide you with what you need, also there is [this](http://www.codeproject.com/Articles/1940/XGetopt-A-Unix-compatible-getopt-for-MFC-and-Win)?

**Comment by mrboggieman** [comment]
I can get it to compile on Windows (and working) by just dropping these files into the directory:

[liblmdb_win.zip](https://github.com/Venemo/node-lmdb/files/94524/liblmdb_win.zip)

**Comment by delaneyj** [comment]
Can those files be added or a binary for Windows be provided?  I have a catch 22 where npm won't create the directly until its finished installing but can't finish install without those headers.

**Comment by mrboggieman** [comment]
@delaneyj You can download the node-lmdb source from git, add the files posted above to 'node-lmdb-master/libraries/liblmdb/' and then just do 'npm install node-lmdb-master' and it will compile the code and you can use 'require("node-lmdb")' as normal

**Comment by delaneyj** [comment]
wouldn't it be more universal to just include the 3 headers?  This way is making the use of lmdb a special  case in a normal npm workflow.

**Comment by Venemo** [comment]
@mrboggieman Can you give some more explanation on what exactly those files are? Could I include them in the source tree?

**Comment by delaneyj** [comment]
Personally I don't know, definitely not a c/c++ node guy..  but if i drop those files into folder with the rest of the code and use `node-gyp configure; node-gyp build` it does in fact build.  I know `io-redis` compiles on Windows without these types of workaround.  Any testing I can do to make this better from a user perspective please let me know.

**Comment by Venemo** [comment]
The other question is that of licensing - do the files come with a license that is compatible with that of `node-lmdb`?

**Comment by delaneyj** [comment]
Gotcha, its iteresting the files linked above appear to be LGPL, but as found [an MIT version](http://web.mit.edu/ghudson/dev/third/krb5/src/util/windows/getopt.c).  The joys of licensing :P

**Comment by mrboggieman** [comment]
@Venemo The files polyfill the linux functionality missing in windows for handling parsing command arguments and os specific calls like fork and wait. To make compiling work with linux and windows it is likely that os specific checks should be used to include the files (rename them to prevent a clash with the linux version). I am no C++ developer though so will leave it up to someone who knows what they are doing. I tried compiling with other polyfills with different licences but had issues linking.

**Comment by Venemo** [comment]
@mrboggieman @delaneyj I'll try to do my best. I'll try to make it work with an MIT-licensed variant but if it doesn't work out, would you guys be okay with the LGPL implementation?

**Comment by mrboggieman** [comment]
@Venemo the licence works for me. As this is a wrapper library I think LGPL is suitable

**Comment by matthiasg** [comment]
testing on windows 10 compared to OS X i would like to understand why example7-largedb states a db site of a constant 16384 MB while the node version on OS X comes up with 2.2GB-2.5GB .. i would assume thats because of system ram compression on OS X, but would prefer some more details on that.

PS: i added the files mentioned above to the windows folder before it would build. @Venemo did you find something MIT based ?

**Comment by Venemo** [comment]
@matthiasg I believe the size difference is because memory-mapped files behave differently on Windows. I recall reading something about this, but can't find the link right now.

**Comment by Venemo** [comment]
Okay, so it seems that as of now, node-lmdb can be built correctly on Windows. It is quite painful though (maybe because I don't develop it on Windows), so I added a section that details how to do it.
