### ISSUE TITLE
Automatic map resizing

### ISSUE THREAD

**Issue by hjerabek** [Venemo/node-lmdb#208]
I came across another LMDB wrapper called [lmdb-js](https://github.com/kriszyp/lmdb-js). It uses a modified version of `mdb.c` which allows automatic map resizing. It seems that this feature would only require a few additional lines of code:

https://github.com/kriszyp/lmdb-js/blob/af6e2b74f57bd07aa11846234c563f356aac4755/dependencies/lmdb/libraries/liblmdb/mdb.c#L3461

IMO the same could be implemented here without breaking anyone's code. Was it deliberately not implemented to keep this wrapper as low-level and unbiased as possible?

**Comment by Venemo** [comment]
I think this feature didn't exist yet (or was considered experimental) when I wrote this module.

**Comment by hjerabek** [comment]
Thanks for the clarifications.
