### ISSUE TITLE
Proper use of Ref and Unref

### ISSUE THREAD

**Issue by Venemo** [Venemo/node-lmdb#21]
This is a followup to the discussion at #20 - I've finally figured out the real reason behind the problem.

The cursors example does something like this:

```js
var dbi1 = env.openDbi({ name: "hello", create: true });
dbi1.drop();
var dbi2 = env.openDbi({ name: "hello", create: true });
// use dbi2
```
The real issue is NOT that the V8 GC ate `dbi2` but that it (correctly) destroyed `dbi1` which in turn called `mdb_dbi_close` on the `MDB_dbi`, while that `MDB_dbi` was still in use by `dbi2`.

The correct solution to this problem:
* Never call `mdb_dbi_close` as it is not required (confirmed by LMDB authors); thus eliminating the above issue

To take correct care of the GC:
* `DbiWrap` needs to `Ref` and `Unref` the `EnvWrap` it uses
* `TxnWrap` needs to `Ref` and `Unref` the `EnvWrap` it uses
* `CursorWrap` needs to `Ref` and `Unref` the `DbiWrap` and `TxnWrap` it uses

**Comment by Venemo** [comment]
I'm assuming that since there weren't any bugreports about it, I'll just close this issue now.

**Comment by RubenVerborgh** [comment]
Woops, yes… doesn't happen often that a TODO of two years is still on my list!
