### ISSUE TITLE
valToBinary() versus valToString()

### ISSUE THREAD

**Issue by shardy-francis** [Venemo/node-lmdb#23]
I've been messing around with "String::NewExternal(new CustomExternalStringResource(&data))" versus "Buffer::New((char*)data.mv_data, data.mv_size, [](char*, void*) -> void { /* Don't need to do anything here, because the data belongs to LMDB anyway */ }, NULL)->handle_" and come to the conclusion that with a 4KB data then the former is about four times faster. It's as if Buffer::New() is not doing the zero copy... Have you done any performance tests? -- Simon

**Comment by Venemo** [comment]
Since this is a Node issue rather than a `node-lmdb` issue, I'll close this issue now.
