### ISSUE TITLE
node v.0.11.x support

### ISSUE THREAD

**Issue by johnnycrab** [Venemo/node-lmdb#25]
Heyhey,
we stumbled across an error when trying to build the module for node v.0.11:
```
../src/node-lmdb.h:58:30: error: expected class name
class EnvWrap : public node::ObjectWrap {
```
This seems to be due to the api changes for native modules when changing from v.0.10.x to v.0.11.x. Do you plan to port node-lmdb to v.0.11 in the very near future? This would be great!  
Maybe this could help: [nan](https://github.com/rvagg/nan)

Thanks a lot and cheers!

**Comment by justmoon** [comment]
Created a PR: #35

CC @MarkSwanson @jackhftang @johnnycrab

**Comment by Venemo** [comment]
@justmoon Thanks! :) Very good job!

**Comment by jackhftang** [comment]
@justmoon Thanks!

**Comment by Venemo** [comment]
@johnnycrab @justmoon So I think I can close this issue now, right?
