### ISSUE TITLE
Reliable way to copy string?

### ISSUE THREAD

**Issue by liukun** [Venemo/node-lmdb#32]
As you have said in doc:

> the data returned by txn.getString() and txn.getBinary() is only valid until the next put operation or the end of the transaction. If you need to use the data later, you will have to copy it for yourself.

What is the most reliable way to copy strings before closing environment and use that string later?

I have tested that `""+string` and `string.substr(0)` would not work and `(" "+string).slice(1)` would work.

**Comment by Venemo** [comment]
It's a tricky question, because (for obvious performance reasons) V8 doesn't like to copy strings. The way you found sounds okay. I also think `JSON.parse(JSON.stringify(yourString))` would work.

**Comment by liukun** [comment]
@Venemo got it! Thanks!
