### ISSUE TITLE
How to list dbis?

### ISSUE THREAD

**Issue by ruffrey** [Venemo/node-lmdb#37]
Thanks for this great lmdb binding. I was not able to find how to list current dbis / subdatabases in an environment. Sorry if this is obvious I am new to lmdb.

**Comment by monquixote** [comment]
I am also having this issue.

**Comment by Venemo** [comment]
There is currently no way in LMDB to list the current dbis, as far as I know. Maybe @hyc (Howard Chu) could comment on whether there is a way to do it.

**Comment by hyc** [comment]
There's no built in method to do so. It doesn't make sense to me to need such a thing, you opened the sub-DBs so you ought to know what they are already.

**Comment by Venemo** [comment]
Well, I could see the benefit of this idea, but as long as it is not supported by the underlying library, I can't support it either.

**Comment by Venemo** [comment]
Let's close this isse. We can reopen it if/when LMDB itself supports such a feature.
