### ISSUE TITLE
Opening second readOnly transaction throws "MDB_BAD_RSLOT"

### ISSUE THREAD

**Issue by lukas-zech-software** [Venemo/node-lmdb#41]
I am trying to do multiple concurrent reads on my environment, however if I try to open a second transaction with the **readOnly** flag this error gets thrown

`Error: MDB_BAD_RSLOT: Invalid reuse of reader locktable slot`

When opening both transactions without the **readOnly** flag the process simply freezes on the second call to `txn.beginTxn()`

The only two concurrent transaction can exist is when one is opened with **readOnly** flag and the other one without, however opening any other transaction on top of those two will lead to one of the errors mentioned above.

The behaviour can easily be reproduced in the example _example3-multiple-transactions.js_ by either removing the **readOnly** flag from the `txn.beginTxn()` call on line 28 or adding it to the call on line 33 (which of course will lead to an error in line 35, but it nonetheless shows the erroneous behaviour)

I would expect a error from opening a second transaction without the **readOnly** flag, as to writing transactions are not allowed, but readOnly transaction should not be limited in number, as the lmdb documentation states:
> . One simultaneous write transaction is allowed, however there is no limit on the number of read transactions even when a write transaction exists.

**Comment by Venemo** [comment]
@lukas-zech-software Thanks for reporting this!

> I am trying to do multiple concurrent reads on my environment, however if I try to open a second transaction with the readOnly flag this error gets thrown

By default, LMDB doesn't allow concurrent reads from the same thread. I'd need to use `MDB_NOTLS` to allow it.

> When opening both transactions without the readOnly flag the process simply freezes on the second call

Yes, this is expected, because the second transaction will wait until the first one finishes (and if your app is single threaded, you basically hit a deadlock).

**Comment by lukas-zech-software** [comment]
Yes, indeed, the second behaviour is expected, as I learned in the meantime. From the docs:

> Once a single read-write transaction is opened, all further attempts to begin one will block until the first one is committed or aborted. 

The first was a bit irritating, but is mentioned in a mailing post by Howard Chu where he states, that the thread should keep it a reference to the read-only transaction and reuse it.
http://www.openldap.org/lists/openldap-technical/201406/msg00016.html

As we only have one thread in NodeJs, reusing the transaction seems the way to go and on simple tests, this works fine. 
I can open multiple cursors on one global transaction and read individually with each of them, even on different named databases.

However I ran into a pretty weird issue when implementing this pattern in my application:

I basically have a small wrapper class around the LMDB environment instance, which holds the reference to the environment as a singleton.
I tried to keep the reference to the global read-only transactions here as well and reuse it everywhere.

This works fine for creating and using single cursors, but fails if a second cursor is created with the global transaction as long as the first one ist still active.

The error throw is this:
`uncaughtException Error: Invalid argument
  at Error (native)`
At the line, where I call 
`new lmdb.Curstor(globalReadOnlyTransaction, database);`

Is this also du to the ** MDB_NOTLS** flag you mentioned or could this come from some other error I made?

**Comment by Venemo** [comment]
@lukas-zech-software I think enabling `MDB_NOTLS` makes sense for `node-lmdb` because node will always be single threaded. The way to use it would depend on the kind of application (eg. for a web app, I'd keep a single readonly transaction per web request).

About your cursor issue: can you please create a simple test case to reproduce it?

**Comment by lukas-zech-software** [comment]
@Venemo 

I created a fork of your repository and changed the cursor example to reflect my use case:
https://github.com/lukas-zech-software/node-lmdb/blob/master/example4-cursors.js

If you clone this repro and run `node example4-cursors.js` you will get an Error `Error: Invalid argument`


Basically all I changed was moving the creation of the environment and the transaction to another module which exports both.

I want to use the same environment and readOnly transaction in my whole application an therefore created this singleton wrapper.

Also in **example4-cursors.js - line 46 ** I open 2 cursors simultaneously to simulate to read accesses at once

Using only one cursor works fine, but trying to open a second cursors causes the error mentioned above


Opening the environment and transaction in the same file works even with multiple cursors, but I need to share the transaction and environment instances in multiple files/instances of my DbReader classes

**Comment by lukas-zech-software** [comment]
I just created a even simpler example here 
https://github.com/lukas-zech-software/node-lmdb/blob/master/example4-cursors_simple.js

Creating the transaction instance in a different function scope than the cursor seems to cause the error.

Are the node bindings somehow bound to the scope object of the calling function?

I don't have a lot of experience with C++ or Node bindings but it might have something to do with the `Nan.HandleScope` object in the Cursor constructor in `cursor.cpp` Line 43

**Comment by lukas-zech-software** [comment]
Sorry for posting so much, but my previous assumption was wrong.

The error happens when a cursor is created on a db which was not opened at the time the transaction was created

Steps to reproduce are therefore:

1. Open Environment 
2. Open _Db1_
3. Begin _Transaction1_
4. Create _Cursor1_ with _Transaction1_ on _Db1_ and start reading
5. Open _Db2_
6. Create _Cursor2_ with _Transaction1_ on _Db2_ and start reading **<<-- Fails**

Creating a cursor with _Transaction1 _ on _Db1_ works but fails fails on _Db2_

Solution to this problem is to reset and renew the transaction whenever a new database is opened:

1. Open Environment 
2. Open _Db1_
3. Begin _Transaction1_
4. Create _Cursor1_ with _Transaction1_ on _Db1_ and start reading
5. Open _Db2_
6. Call `reset` and `renew` on _Transaction1_
7. Create _Cursor2_ with _Transaction1_ on _Db2_ and start reading

Both cursors can be used and _Cursor1_ will also remain its reading position after `renew` was called

Now I see how this makes sense, but I could not find any reference to this behaviour in the lmdb documentation

If you agree I will create a pull request to the cursor example to show this use case.

Any way thanks for your help and your great project

**Comment by Venemo** [comment]
@lukas-zech-software Sure, let me know when the pull request is ready. In the meantime I'll just add MDB_NOTLS which should make your life a bit easier.
