### ISSUE TITLE
Incorrect `dupFixed` argument, always true with `dupSort`

### ISSUE THREAD

**Issue by braydonf** [Venemo/node-lmdb#43]
While doing testing, I've noticed that `dupFixed` in always being set to `true`, when `dupSort` is specified. For example:

```js
var testDbi = env.openDbi({
  name: 'test',
  create: true,
  dupSort: true
});
```
And then putting two values with different sizes:
```js
var value1 = new Buffer(new Array(8));
var value2 = new Buffer(new Array(4));
txn.putBinary(testDbi, key, value1);
txn.putBinary(testDbi, key, value2);
```

Will give the error:
```
Error: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size
```

From reading [documentation](http://symas.com/mdb/doc/group__mdb__dbi__open.html#ga5acc26f80668d1ebc31265d178c69338) the size of the value should only need to be fixed when `MDB_DUPFIXED` is specified.

**Comment by Venemo** [comment]
@braydonf Thanks for reporting this. Can you give me a minimal test case that reproduces the problem?
