### ISSUE TITLE
Require statement include direct path to bindings

### ISSUE THREAD

**Issue by braydonf** [Venemo/node-lmdb#44]
Requiring node-lmdb currently is required with the full path:

```js
var lmdb = require('node-lmdb/build/Release/node-lmdb');
```

Which when switching between bindings that are compiled with the debug flag, the require statements need to be updated to:

```js
var lmdb = require('node-lmdb/build/Debug/node-lmdb');
```

This could be automatically handled with the [bindings](https://www.npmjs.com/package/bindings) module or [prebuild](https://www.npmjs.com/package/prebuild), and compatible with both with:

```js
var lmdb = require('node-lmdb');
```

**Comment by Venemo** [comment]
@braydonf If you download the module from npm, `require('node-lmdb')` should just work, doesn't it?

**Comment by braydonf** [comment]
Yep, so I just realized that `var lmdb = require('node-lmdb');` should work already since package.json specifies `./build/Release/node-lmdb`. However if compiled with debug this would need to be updated.

**Comment by Venemo** [comment]
@braydonf So what's your suggestion?
