### ISSUE TITLE
Callback interface is expensive

### ISSUE THREAD

**Issue by Matt-Esch** [Venemo/node-lmdb#51]
A callback-based interface adds a significant amount of overhead. The synchronous methods should ideally return values instead of using a callback.

**Comment by Venemo** [comment]
@Matt-Esch Which methods are you talking about, specifically?

**Comment by Venemo** [comment]
@russtee I'm looking forward to getting your feedback about this as well. :)

**Comment by russtee** [comment]
We use lmdb synchronously for all operations whenever possible and the extra code overhead to handle the cursor callbacks seems unnecessary.

LMDB is very fast especially when running on SSD's. 

That said on slower machines callbacks could be handy and would fit well into the node streams system for iteration operations.

**Comment by Venemo** [comment]
One way to go about this is to create a JavaScript object and return that instead of calling a callback. The proposed object could have a `key` and  `data` property. Would something like this suit your needs?

For example,

```js
var x = cursor.getCurrentString();
console.log(x.key, x.data);
```

**Comment by russtee** [comment]
that would work. However do I actually need the key as I would most likely already have it from the cursor iteration function?

**Comment by Venemo** [comment]
What do you mean? Can you post some example code of how you would be comfortable using it?

**Comment by russtee** [comment]
```
for (var c = cursor.goToFirst(); c; c=cursor.goToNext()) {
   var val = cursor.getCurrentBinary();
```
As a hack/test I changed my local copy of the library to return the value instead of the key when 'convertFunc' was set.

Probably not they way you would want to do it but it seems to work and solves the problem we have.

**Comment by Venemo** [comment]
But then this would make it impossible to see the current key.

**Comment by russtee** [comment]
We use the value from goToNext etc. as we always call that prior.

**Comment by Venemo** [comment]
I see. Okay, let me think about it a bit more and I'll get back to you guys.

**Comment by rneilson** [comment]
Let me +1 just returning the value from getCurrent*() -- you'll always have the current key as the return value of cursor.goTo*(), and the callback makes any iteration (by loop, or especially by  forEach(), map(), reduce(), etc) much clumsier.

**Comment by rneilson** [comment]
I've submitted PR #78, which I think is a workable compromise. The callback interface is still present, if you need both key and value together, but `getCurrentString()` and friends return the value instead of the key regardless, meaning they can be used without a callback if desired. Also, there's no extra conversion overhead, since I merely relocated the call to `convertFunc(cw->data)`.

**Comment by Venemo** [comment]
Thank you @rneilson for your work. This is much better than what we had before, so it's a step in the right direction. :)

**Comment by rneilson** [comment]
@Venemo You're quite welcome.

**Comment by Venemo** [comment]
I believe we can agree to close this issue now, the current API doesn't require the use of callback anymore.
