### ISSUE TITLE
Publish v0.4.0

### ISSUE THREAD

**Issue by Matt-Esch** [Venemo/node-lmdb#52]
v0.3.0 is the latest published version, v0.4.0 patches a memory leak

**Comment by Venemo** [comment]
@Matt-Esch I'll review all the code and publish a new version this week. Thank you for your patience!

**Comment by yetzt** [comment]
@Venemo next week was some weeks ago now. i'd really like to reference this module in my package.json from npm instead of from git. would you please be so kind and `npm publish` now?

**Comment by Venemo** [comment]
Sorry guys. I published it now!

**Comment by Venemo** [comment]
New version number is 0.4.1 :)

**Comment by yetzt** [comment]
yay, thanks!
