### ISSUE TITLE
add support for non named databases

### ISSUE THREAD

**Issue by russtee** [Venemo/node-lmdb#53]
In order to access non named databases mdb_dbi_open needs to be called with NULL for the value of 'name'.

Currently this is not possible and so there is no way to access the data saved from other node lmdb modules such as https://github.com/rvagg/lmdb.

**Comment by Venemo** [comment]
@russtee There is only one non-named database and multiple named databases. Are you aware that you can't use the non-named one if you also use the named one? Therefore it isn't very useful.

**Comment by russtee** [comment]
Understand that, however it's very useful if you're porting your data from a db built using rvaggs lmdb module to this one. (which we are)

**Comment by Venemo** [comment]
@russtee I see. It shouldn't be to hard to do it, let me take a look. :)

**Comment by russtee** [comment]
Great stuff, much appreciated.

**Comment by Venemo** [comment]
@russtee I committed some code to support using the unnamed database, along with some docs and an example on how to use it. Please take a look and report back if this is okay for you.

**Comment by russtee** [comment]
worked first time. thanks a lot.

**Comment by Venemo** [comment]
Awesome, glad I could help! :)
