### ISSUE TITLE
sync version of cursor getters

### ISSUE THREAD

**Issue by russtee** [Venemo/node-lmdb#54]
Currently the cursor get functions getCurrentString, getCurrentNumber, getCurrentBinary and getCurrentBoolean return the value asynchronously.

Would it be possible to add versions that return the value synchronously in a similar way to the general get functions as it would make iterator code much less complex?

**Comment by Venemo** [comment]
I believe this is what issue #51 is also about. Please let's discuss it there and let's close this one. :)
