### ISSUE TITLE
Node.js 6.x problems

### ISSUE THREAD

**Issue by AlgoTrader** [Venemo/node-lmdb#58]
All the examples show lots of warnings like this

```
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.
```

and follow huge stack traces. When node 6.x will get support?

**Comment by Venemo** [comment]
@AlgoTrader Thanks for reporting this! I'll take a look and see what's the problem there.

**Comment by Venemo** [comment]
@AlgoTrader Have you tried with the latest version?

**Comment by AlgoTrader** [comment]
latest npm

**Comment by Venemo** [comment]
@AlgoTrader Can you please give me some more details about the problem? Ie. which exact version of node did you use, which exact version of node-lmdb did you use? Also, what errors did you get? (If it is long, please use a pastebin and post a link to the paste here.)

**Comment by AlgoTrader** [comment]
Just npm install node-lmdb. Node is
```
{ http_parser: '2.7.0',
  node: '6.1.0',
  v8: '5.0.71.35',
  uv: '1.9.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '48',
  openssl: '1.0.2h' }
```

run `node any_example.js` and you see the stuff:

```
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x22896bdc0dc1 <JS Object>#0#
    1: .node [module.js:568] [pc=0x19743bd471c4] (this=0x2a32720b84f1 <an Object with map 0x5ab7a617b31>#1#,module=0x2a32720bfbe9 <a Module with map 0x5ab7a618109>#2#,filename=0x2a32720bfae1 <String[70]: /opt/projects/test/node_modules/node-lmdb/build/Release/node-lmdb.node>)
    2: load [module.js:456] [pc=0x19743bd39d52] (this=0x2a32720bfbe9 <a Module with map 0x5ab7a618109>#2#,filename=0x2a32720bfae1 <String[70]: /opt/projects/test/node_modules/node-lmdb/build/Release/node-lmdb.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x19743bd3987d] (this=0x22896bd04189 <undefined>,module=0x2a32720bfbe9 <a Module with map 0x5ab7a618109>#2#,filename=0x2a32720bfae1 <String[70]: /opt/projects/test/node_modules/node-lmdb/build/Release/node-lmdb
```

New node uses very modern V8, you have to update C bindings

**Comment by Venemo** [comment]
Thanks @AlgoTrader for the details, I'll install node 6 myself and see what I can do about this.

**Comment by Venemo** [comment]
Okay, I can reproduce the issue on node v6.2, I'll see what I can do about it. Apart from the weird stack traces that it prints, the example code seems to work fine otherwise.
