### ISSUE TITLE
Managing LMDB dependency docs

### ISSUE THREAD

**Issue by braydonf** [Venemo/node-lmdb#61]
The docs at https://github.com/Venemo/node-lmdb#managing-the-lmdb-dependency seem to be outdated, has the process changed?

**Comment by Venemo** [comment]
Thank you @braydonf for spotting this. I believe the only thing that's changed is the address of the LMDB repo. I'll fix the readme to reflect that.

**Comment by braydonf** [comment]
I wasn't able to get the subtree portion to work properly either after using an updated git url. I ended up cloning openldap (from http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=summary) at the LMDB tag in another repository and copying the files into `libraries/liblmdb`.

**Comment by Venemo** [comment]
Looks like the last time it was updated the proper instructions weren't followed, that's why it isn't located at the said prefix. Sorry for the inconvenience; I'll handle this. :)

**Comment by Venemo** [comment]
@braydonf I've updated the lmdb dependency, it should work properly now. Can you please check if it works for you?

**Comment by braydonf** [comment]
It works, though it's not necessary to run `git subtree add` as the path already exists *(as stated)*. The other question is specifying which tag to pull from?

**Comment by braydonf** [comment]
I think it's just using the tag instead of HEAD:
```
$ git subtree pull --prefix=dependencies/lmdb lmdb LMDB_0.9.18 --squash
From github.com:LMDB/lmdb
 * tag               LMDB_0.9.18 -> FETCH_HEAD
Subtree is already at commit 627c85175007bdd95c87054e4816dcf46ddff75c.
```

Looks good to me!

**Comment by Venemo** [comment]
@braydonf Yes, you can use any ref, not just HEAD. I used the LMDB_0.9.18 tag like you said.
