### ISSUE TITLE
Handling two write transactions attempted

### ISSUE THREAD

**Issue by braydonf** [Venemo/node-lmdb#68]
As there can only be one write transaction at time, attempting to begin two write transactions with the same environment will result in the process locking that is impossible for the code to exit without being terminated externally. 

``` js
var txn1 = env.beginTxn();
var txn2 = env.beginTxn();
```

A few ideas:
- throw an error on the second attempt
- return null
- asynchronous callback option that could wait until a write transaction could be obtained

**Comment by braydonf** [comment]
Here is a possible test case:
```js
describe('Write Lock', function() {
  var env;
  var dbi;
  before(function() {
    env = new lmdb.Env();
    env.open({
      path: testDirPath,
      maxDbs: 10,
      mapSize: 16 * 1024 * 1024 * 1024
    });
    dbi = env.openDbi({
      name: 'mydb6',
      create: true
    });
  });
  after(function() {
    dbi.close();
    env.close();
  });
  it('will throw error if write transaction already open', function() {
    var txn1 = env.beginTxn();
    (function() {
      var txn2 = env.beginTxn();
    }).should.throw(Error);
  });
});
```

**Comment by Venemo** [comment]
I believe the proper course of action would be to simply throw an error on the second attempt. This is the simplest and easiest-to-understand solution. :)

**Comment by braydonf** [comment]
It looks like `env->me_txn` could be used to check if there is an existing write transaction for the environment.

http://lmdb.tech/doc/group__internal.html#a41f4abc70ee54d822f4674d48d4c4461

**Comment by Venemo** [comment]
It is generally unwise to use the internals of any library in custom code, because there is no API guarantee for it to work the same way in new versions.

**Comment by braydonf** [comment]
Indeed, I wasn't successful is using `me_txn`, and received this error when compiling:

```
../src/txn.cpp:58:16: error: invalid use of incomplete type ‘MDB_env {aka struct MDB_env}’
     if (ew->env->me_txn) {
```

**Comment by Venemo** [comment]
@braydonf How would you feel about simply throwing an error on trying to open a second write transaction in the same process?

**Comment by braydonf** [comment]
Sounds good to me.

**Comment by braydonf** [comment]
I've been using an `async.priorityQueue` with a concurrency of 1 and scheduling write tasks to make sure that only one write transaction is open a time.

**Comment by Venemo** [comment]
It now throws an error when you try to open a second write transaction. Sorry for taking so long to implement it.
