### ISSUE TITLE
cursor.goToDup doesn't work when keyIsUint32 is used

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [Venemo/node-lmdb#76]
var lmdb, env, dbi;

lmdb = require('node-lmdb');
env = new lmdb.Env();
env.open({
    // Path to the environment
    path: "./testdata",
    // Maximum number of databases
    maxDbs: 10
});

try {
    // If the database exists, drop it
    dbi = env.openDbi({
       name: "example5-dupsort-uint",
       dupSort: true,
       keyIsUint32: true,
    });
    dbi.drop();
}
catch (err) {}
dbi = env.openDbi({
   name: "example5-dupsort-uint",
   create: true,

   //dupSort: true,
   //dupFixed: true,
   //integerDup: true
   
   dupSort: true,
   keyIsUint32: true,

});   

console.log("ensured database is empty");

var printFunc = function(key, data) {
    console.log("---------->  key:", key);
    console.log("----------> data:", data);
}

var txn, cursor;

txn = env.beginTxn();

txn.putString(dbi, 1, "1-hello");
txn.putString(dbi, 2, "2-apple");
txn.putString(dbi, 3, "3-orange");
txn.putString(dbi, 2, "4-apple");
txn.putString(dbi, 1, "5-hello");
txn.putString(dbi, 4, "6-appricot");
txn.putString(dbi, 1, "7-hello");

txn.commit();

console.log("wrote test values");

txn = env.beginTxn({ readOnly: true });
cursor = new lmdb.Cursor(txn, dbi);

console.log("goToRange '5'");
cursor.goToRange(5);
cursor.getCurrentString(printFunc);

console.log("goToNext");
cursor.goToNext();
cursor.getCurrentString(printFunc);

console.log("goToNext");
cursor.goToNext();
cursor.getCurrentString(printFunc);

console.log("goToNext");
cursor.goToNext();
cursor.getCurrentString(printFunc);

console.log("goToDup 2, '4-apple'");
cursor.goToDup(2, "4-apple");
cursor.getCurrentString(printFunc);

console.log("goToDupRange 1, '0-hello'");
cursor.goToDup(1, "0-hello");
cursor.getCurrentString(printFunc);

console.log("");
console.log("iterating through a duplicate key: if-do-while");

var key = 1;

if (cursor.goToRange(key) === key) {
    do {
        cursor.getCurrentString(function(key, data) {
            // do something with data
            console.log(key, data);
        });
    } while (cursor.goToNextDup());
}

console.log("");
console.log("iterating through a duplicate key: for");

var key = 2;

for (var found = (cursor.goToRange(key) === key); found; found = cursor.goToNextDup()) {
    cursor.getCurrentString(function(key, data) {
        // do something with data
        console.log(key, data);
    });
}

cursor.close();
txn.abort();
dbi.close();
env.close();

**Comment by rneilson** [comment]
This isn't actually a bug with `keyIsUint32`, it's a bug with `goToDup()` and 'goToDupSort()` with string or buffer data, where the data is being initialized from the *third* argument, not the second. Try repeating the 2nd argument in your calls to `goToDup()` and you'll see what I mean. I've submitted PR #77 for a fix.

**Comment by Venemo** [comment]
@rneilson Awesome, thank you for spotting and fixing this issue!

**Comment by rneilson** [comment]
@Venemo No problem!
