### ISSUE TITLE
Can not delete when dupSort is true

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [Venemo/node-lmdb#79]
Docs:

http://lmdb.tech/doc/group__mdb.html
mdb_del (MDB_txn *txn, MDB_dbi dbi, MDB_val *key, MDB_val *data)

I guess the reason is nullptr at the end:

https://github.com/Venemo/node-lmdb/blob/master/src/txn.cpp
int rc = mdb_del(tw->txn, dw->dbi, &key, nullptr);

**Comment by rneilson** [comment]
I noticed that just now, too.

Now that `goToDup()` is working, I've been using `cursor.del()` instead of `txn.del()`, but now that I have an inkling of what's going on, I'll see if I can get a patch together soon, and hopefully @Venemo can merge it.

**Comment by rneilson** [comment]
PR #80 is in. If you need it now, you can get it from my branch: rneilson/node-lmdb@10ef6a7c3a25e730ec133c74a4d943f129e555ff
