### ISSUE TITLE
Deprecation warning on node v6

### ISSUE THREAD

**Issue by mzedeler** [Venemo/node-lmdb#81]
node-lmdb produces a lot of deprecation warnings when run with node.js version 6 and up:

v8::ObjectTemplate::Set() with non-primitive values is deprecated

The call will be deprecated in version 7, but it is already quite annoying because the screen fills with deprecation warnings...

**Comment by braydonf** [comment]
Are you running the latest master, because some of the warnings have been cleared with: https://github.com/Venemo/node-lmdb/commit/bda3aa5ff0bd01c87dd40cde0def05ce7884582e

**Comment by braydonf** [comment]
There are still a few deprecation messages when running `node-gyp rebuild` with Node.js v6.

**Comment by mzedeler** [comment]
I didn't build from master - just the latest version available with npm (version 0.4.1).

But it's great to know that you've started looking into getting them fixed.

**Comment by Venemo** [comment]
Try latest master, @braydonf submitted a pull request that improves on this.

**Comment by Venemo** [comment]
@mzedeler Do you still experience this problem?

**Comment by Venemo** [comment]
I believe I have fixed the last deprecation warnings now, so I'm closing the issue. Please reopen if you find any more problems with it.
