### ISSUE TITLE
Build errors with node-lmdb@0.4.3 (node v7.2.1 os x 10.11.6 XCode 8.2)

### ISSUE THREAD

**Issue by andrenventer** [Venemo/node-lmdb#88]
➜  ~ npm -g install node-lmdb                      

> node-lmdb@0.4.3 install /usr/local/lib/node_modules/node-lmdb
> node-gyp rebuild

  CC(target) Release/obj.target/node-lmdb/dependencies/lmdb/libraries/liblmdb/mdb.o
../dependencies/lmdb/libraries/liblmdb/mdb.c:9846:46: warning: data argument not used by format string [-Wformat-extra-args]
                                (int)mr[i].mr_pid, (size_t)mr[i].mr_tid, txnid);
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/node-lmdb/dependencies/lmdb/libraries/liblmdb/midl.o
  CXX(target) Release/obj.target/node-lmdb/src/node-lmdb.o
  CXX(target) Release/obj.target/node-lmdb/src/env.o
  CXX(target) Release/obj.target/node-lmdb/src/misc.o
  CXX(target) Release/obj.target/node-lmdb/src/txn.o
../src/txn.cpp:293:52: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
            *((double*)data.mv_data) = dataHandle->ToNumber()->Value();
                                                   ^
/Users/nomad/.node-gyp/7.2.1/include/node/v8.h:8406:22: note: 'ToNumber' has been explicitly marked deprecated here
Local<Number> Value::ToNumber() const {
                     ^
1 warning generated.
  CXX(target) Release/obj.target/node-lmdb/src/dbi.o
  CXX(target) Release/obj.target/node-lmdb/src/cursor.o
  SOLINK_MODULE(target) Release/node-lmdb.node
/usr/local/lib
└── node-lmdb@0.4.3

**Comment by Venemo** [comment]
@andrenventer Hi! Thanks for reporting this. I don't see any errors in the build you posted, only a few warnings. Can you please elaborate on what issue you see exactly?

**Comment by aholstenson** [comment]
I'm seeing a similar issue on OS X 10.10:
```
  SOLINK_MODULE(target) Release/node-lmdb.node
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
```

Modifying `binding.gyp` to use MACOSX_DEPLOYMENT_TARGET seems to solve the issue. I'm unsure if this has any side effects though, I have not tried compiling on a older or newer OS version.

Diff for change:
```
diff --git a/binding.gyp b/binding.gyp
index 94be624..b5a33b5 100644
--- a/binding.gyp
+++ b/binding.gyp
@@ -33,7 +33,8 @@
         }],
         ["OS=='mac'", {
           "xcode_settings": {
-            "OTHER_CPLUSPLUSFLAGS" : ["-std=c++11", "-mmacosx-version-min=10.7"],
+            "OTHER_CPLUSPLUSFLAGS" : ["-std=c++11"],
+            "MACOSX_DEPLOYMENT_TARGET": "10.7",
             "OTHER_LDFLAGS": ["-std=c++11"],
             "CLANG_CXX_LIBRARY": "libc++"
           }
```

**Comment by Venemo** [comment]
They should be similar according to [this StackOverflow post](http://stackoverflow.com/questions/25352389/difference-between-macosx-deployment-target-and-mmacosx-version-min-compiler-op) but anyway if it does work with this change, can you please submit a pull request?

**Comment by Venemo** [comment]
Since #89 is supposed to fix this, I'm closing it now.
