### ISSUE TITLE
LMDB Safe String Buffer Over-read

### ISSUE THREAD

**Issue by da77a** [Venemo/node-lmdb#93]
When copying from lmdb storage to the "safe" Node string, no check is made that the data being copied is zero terminated. In particular, this problem shows up when reading keys or data that, if written by node-lmdb, were written as binary, or if written to the lmdb database by some other code, that code did not elect to use UTF-16 with zero terminator as its data/string format. Behaviour is variable - typically it returns a string that is actually constructed (with an implicit assumption of UTF-16 encoding of the data read) from the actual key plus some or all of the value. Other results, including crashes, are possible.

See more discussion on this and related issues in #84 (Goto functions return garbage strings).

**Comment by Venemo** [comment]
This bug was introduced by this commit, in july 2016: https://github.com/Venemo/node-lmdb/commit/9f56eeb428e4fc707bebfb5af1b227b168ef4d13 when the old `valToString` function was renamed to `valToStringUnsafe` and a new implementation of `valToString` (intended to be safe) was introduced.

I also checked the V8 docs: https://v8docs.nodesource.com/node-4.6/d2/db3/classv8_1_1_string.html#a237a2b794f31d8c60d9561ad3b30248ea59086564b4911ba69b7b8cdd0ac439b4

* It does not require zero termination when a string length is specified, so we can use `Nan::New<String>(const uint16_t *buffer, int length)`
* It does not produce zero termination when a string length is specified when using `v8::String::Write`

**Comment by da77a** [comment]
I trust the reference to v8::String::Write with a length is not suggesting a change that will use it (and not include 0 terminator)? Obviously that will break existing databases.

And as per all the talk in #84  thread, the lack of 0 terminator on read  should be detected and treated as an error (the error is: "This value cannot have been written by existing node-lmdb string interface so can't be read via it either.") or at least be detectable (by refusing to return a string type and returning a Buffer instead).

**Comment by Venemo** [comment]
The current node-lmdb implementation **always** adds a zero-terminator automatically when saving a string:
https://github.com/Venemo/node-lmdb/blob/master/src/misc.cpp#L171

This zero-terminator however is added "just in case", and is not actually passed to V8, when using the `CustomExternalStringResource` class:
https://github.com/Venemo/node-lmdb/blob/master/src/misc.cpp#L181

**Comment by Venemo** [comment]
So the only bug here that I can think of is when a string contains an extra zero in the middle, eg. if you save `"Hello \0 world!"` it will be read back as `"Hello "` because of the faulty `valToString` implementation.

**Comment by Venemo** [comment]
@da77a I wrote a test case for the `"Hello \0 world"` case, and it indeed fails. But since the zero terminator is automatically added to the database, I don't think there are other errorneous cases. But if you can give me another failing test case, I'll investigate it further.

**Comment by da77a** [comment]
@Venemo - I only created this separate incident because you stated the 0 terminator issue was unrelated to issue #84 , in which I was discussing it. I actually do think it is related and the whole problem is described there. If you think undefined behaviour (anything from "garbage" to a bus error) on trying to read something that was written in a different format is acceptable that's where we disagree. If you think that such behaviour is unacceptable then we would presumably both agree that all that is needed is an error when trying to convert a string that doesn't have a 0 terminator. As I said above.

**Comment by Venemo** [comment]
@da77a Okay, I believe now I understand your point. Sorry for the confusion. Looks like this is indeed the same issue as #84. Let's keep it in #84 then.
