### ISSUE TITLE
Cursor functions that take key parameters leak

### ISSUE THREAD

**Issue by da77a** [Venemo/node-lmdb#94]
The argToKey function returns a "deleter" function used by get/put fns to clean up the "in" parameter. Cursor goToKey etc discard this return value.

**Comment by Venemo** [comment]
@da77a Nice catch! I've fixed this with https://github.com/Venemo/node-lmdb/commit/6244c952b34882e546fb8e56c76c8090f6397d5d

**Comment by Venemo** [comment]
Can you please verify that it works correctly now?

**Comment by Venemo** [comment]
Oh my god... maybe this is related to #31

**Comment by da77a** [comment]
Works for me. Just a note though - I'm not sure what the motivation is for hanging on to the allocation (and the deleter in CursorWrap.freeKey) in cases where mdb_cursor_get does not change the key mdb. The lmdb interface is quirky with its use of in/out parameters and the MDB_cursor_op parameter to specify what should be done, but as documented (and the lmdb code seems to agree) the ONLY call that won't change the key mdb is when the cursor op is MDB_SET_KEY. And as this will only be set when there IS a new key parameter, it seems that in all other cases the key mdb is an OUT parameter and will ALWAYS point to memory owned by lmdb (or be null). I haven't properly tested this but that is what the specs say... Probably not worth worrying about - your change works... It just looked "odd" hanging onto the key "just in case".

**Comment by da77a** [comment]
Ah - actually - I think there is still a tiny leak... destructor needs to clean up...

Just adding

 if (freeKey)  freeKey(key);

to  CursorWrap::~CursorWrap()

should fix it (untested)...

Alternatively see previous comment about being able to free straight after the call to mdb_cursor_get regardless of whether the cursor mdb was modified by lmdb - always freeing the "current" key by end of call to getCommon seems fine to me.

**Comment by Venemo** [comment]
@da77a Ooops! Looks like this isn't as simple as we thought. I implemented your suggestion of freeing the key immediately, but as of now, `cursor.goToKey` is broken. Looks like using `MDB_SET_KEY` instead of `MDB_SET` will fix it.

**Comment by Venemo** [comment]
@da77a Looks like we can't get away with this so easily. `goToDup` uses `MDB_GET_BOTH` and the key doesn't point inside LMDB. So in that case, `cursor` will have to hold on to the key and free it later.
