### ISSUE TITLE
Possible to expose Immutable.js like interface?

### ISSUE THREAD

**Issue by NodeGuy** [Venemo/node-lmdb#95]
I just discovered LMDB and understand that under the hood it uses COW.  Would it be a lot of work to expose a persistent API similar to [Immutable.js](https://facebook.github.io/immutable-js/)'s?

**Comment by Venemo** [comment]
@NodeGuy Taking a look at your link, as far as I see, the node-lmdb API is already quite similar (although the method names are different, but the semantics are similar).

If you have a specific proposal in mind, I'd be happy to listen to your idea.

**Comment by NodeGuy** [comment]
Thank you for your consideration.  It inspired me to dig more deeply into the documentation and there I was able to see that what I'm asking for is long-lived transactions and that LMDB is not designed to support them.  Thanks anyway.
