### ISSUE TITLE
Request option to create new databases within transactions.

### ISSUE THREAD

**Issue by NodeGuy** [Venemo/node-lmdb#99]
I can't create a new database within a transaction like this:

```
// Create transaction
var txn = env.beginTxn();

var dbi = env.openDbi({
   name: "mydb2",
   create: true
});
```

node-lmdb hangs when it gets to `env.openDbi`.

Being able to create a new database while within a write transaction would be very useful to me and is allowed by the Python binding: https://lmdb.readthedocs.io/en/release/#lmdb.Environment.open_db

**Comment by Venemo** [comment]
@NodeGuy 
Thanks for your bug report. The problem here is that when you set `create:true`, `openDbi` tries to be smart and creates its own write transaction to create your database. (Which obviously fails because there is already a write transaction.) The proper solution here would be to allow the user to supply a transaction to `openDbi`. I'll look into it.

Can you tell me what exactly would you like to achieve here?  
Maybe we could find a workaround for you until this is fixed.

**Comment by NodeGuy** [comment]
Thanks for asking.  I've just implemented my own workaround which is to specify a single unnamed database and to implement sub-databases in JavaScript.  I don't expect that it's as performant as using LMDB's implementation.

My code creates and destroys databases dynamically in the course of making other changes to the key-value store.  For example, when I add a new `goal` to the `goals` database I also create a new `dependenciesOf` database to use as a query index for it.  When I delete the `goal` then I drop the `dependenciesOf` index database at the same time.  To avoid possible corruption I want these database creates and drops to happen within the `goal` changing transactions.

**Comment by Venemo** [comment]
@NodeGuy The `openDbi` function now has a new option called `txn`, with which you can specify your own transaction. There is also a new example that demonstrates how you can use it: https://github.com/Venemo/node-lmdb/blob/master/examples/11-createdbi-usertxn.js

**Comment by Venemo** [comment]
Please verify if it works for you. :)

**Comment by Venemo** [comment]
@NodeGuy `dbi.drop` also received the ability to use user-supplied transactions, so your use-case should be covered now.

Example use:

```js
var txn = env.beginTxn();
var dbi = env.openDbi({ name: "myDbi", create: true, txn: txn });
// ...
dbi.drop({ txn: txn });
// ...
txn.commit();
```

**Comment by Venemo** [comment]
I'm closing this issue now. Please reopen if you have any trouble with this feature.

**Comment by NodeGuy** [comment]
Wow, fantastic!  Thank you for being so responsive!  It works great.

LMDB is an exceptional piece of software and I'm grateful that you've made it easy to use from Node.js.  Thank you.

**Comment by Venemo** [comment]
Thank you @NodeGuy I'm glad you like it!
